default_platform :ios

platform :ios do
  lane :lint do
    pod_lib_lint(skip_tests: true)
  end

  lane :release do
    version = read_podspec['version']

    pod_lib_lint
    pod_push(allow_warnings: true, verbose: true)
  end
end